# Generated by Django 5.2 on 2026-08-22 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetieme', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_staff_reply', models.BooleanField(default=False, help_text='is admin reply message?')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.order')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
    ]
