# Generated by Django 5.2 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
