# Generated by Django 5.2 on 2026-08-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='ordercomment',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
    ]
