# Generated by Django 5.2 on 2026-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_updated_datetieme_order_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
