# Generated by Django 5.2 on 2026-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_session_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_failed', 'Payment Failed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
