# Generated by Django 5.2 on 2026-08-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sell_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
    ]
