# Generated by Django 5.2 on 2026-08-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetieme', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Expired', 'Expired'), ('Refund', 'Refund')], default='Pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='HKD', max_length=10)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Simulated', 'Simulated')], default='Simulated', max_length=20)),
                ('order', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
