# Generated by Django 5.2 on 2026-08-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
    ]
