# Generated by Django 5.2 on 2026-08-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_datetieme',
            new_name='updated_datetime',
        ),
    ]
